// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for ROS 2 Educational Module
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System',
      items: [
        {
          type: 'doc',
          id: 'module-1/chapter-1-ros2-basics',
          label: 'Chapter 1: ROS 2 Basics'
        },
        {
          type: 'doc',
          id: 'module-1/chapter-2-rclpy-bridge',
          label: 'Chapter 2: Python-ROS Bridge (rclpy)'
        },
        {
          type: 'doc',
          id: 'module-1/chapter-3-urdf-modeling',
          label: 'Chapter 3: Humanoid Description (URDF)'
        }
      ]
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        {
          type: 'doc',
          id: 'module-2-digital-twin/index',
          label: 'Module Introduction'
        },
        {
          type: 'category',
          label: 'Chapter 1: Physics Simulation in Gazebo',
          items: [
            {
              type: 'doc',
              id: 'module-2-digital-twin/physics-gazebo/setup',
              label: 'Setup Guide'
            },
            {
              type: 'doc',
              id: 'module-2-digital-twin/physics-gazebo/gravity-collisions',
              label: 'Gravity and Collisions'
            },
            {
              type: 'doc',
              id: 'module-2-digital-twin/physics-gazebo/robot-control',
              label: 'Robot Control'
            },
            {
              type: 'doc',
              id: 'module-2-digital-twin/physics-gazebo/exercises',
              label: 'Exercises'
            }
          ]
        },
        {
          type: 'category',
          label: 'Chapter 2: Sensor Integration',
          items: [
            {
              type: 'doc',
              id: 'module-2-digital-twin/sensors/lidar-setup',
              label: 'LiDAR Setup'
            },
            {
              type: 'doc',
              id: 'module-2-digital-twin/sensors/camera-imu-setup',
              label: 'Camera and IMU Setup'
            },
            {
              type: 'doc',
              id: 'module-2-digital-twin/sensors/ros2-integration',
              label: 'ROS 2 Integration'
            },
            {
              type: 'doc',
              id: 'module-2-digital-twin/sensors/exercises',
              label: 'Exercises'
            }
          ]
        },
        {
          type: 'category',
          label: 'Chapter 3: Unity Visualization',
          items: [
            {
              type: 'doc',
              id: 'module-2-digital-twin/rendering-unity/unity-setup',
              label: 'Unity Setup'
            },
            {
              type: 'doc',
              id: 'module-2-digital-twin/rendering-unity/import-models',
              label: 'Model Import'
            },
            {
              type: 'doc',
              id: 'module-2-digital-twin/rendering-unity/lighting-rendering',
              label: 'Lighting and Rendering'
            },
            {
              type: 'doc',
              id: 'module-2-digital-twin/rendering-unity/exercises',
              label: 'Exercises'
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        {
          type: 'doc',
          id: 'module-3-ai-robot-brain/index',
          label: 'Module Introduction'
        },
        {
          type: 'doc',
          id: 'module-3-ai-robot-brain/intro',
          label: 'Introduction'
        },
        {
          type: 'doc',
          id: 'module-3-ai-robot-brain/quickstart',
          label: 'Quickstart Guide'
        },
        {
          type: 'doc',
          id: 'module-3-ai-robot-brain/troubleshooting',
          label: 'Troubleshooting'
        },
        {
          type: 'doc',
          id: 'module-3-ai-robot-brain/deliverables',
          label: 'Deliverables'
        },
        {
          type: 'doc',
          id: 'module-3-ai-robot-brain/success_criteria_verification',
          label: 'Success Criteria Verification'
        },
        {
          type: 'category',
          label: 'Isaac Sim: Photorealistic Simulation',
          items: [
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/isaac-sim/index',
              label: 'Overview'
            },
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/isaac-sim/setup',
              label: 'Setup Guide'
            },
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/isaac-sim/photorealistic-simulation',
              label: 'Photorealistic Simulation'
            },
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/isaac-sim/synthetic-data-generation',
              label: 'Synthetic Data Generation'
            },
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/isaac-sim/exercises',
              label: 'Exercises'
            }
          ]
        },
        {
          type: 'category',
          label: 'Isaac ROS: VSLAM and Perception',
          items: [
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/isaac-ros/index',
              label: 'Overview'
            },
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/isaac-ros/vslam-setup',
              label: 'VSLAM Setup'
            },
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/isaac-ros/perception-pipelines',
              label: 'Perception Pipelines'
            },
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/isaac-ros/ai-navigation',
              label: 'AI Navigation'
            },
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/isaac-ros/exercises',
              label: 'Exercises'
            }
          ]
        },
        {
          type: 'category',
          label: 'Nav2: Path Planning for Humanoid Movement',
          items: [
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/nav2/index',
              label: 'Overview'
            },
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/nav2/path-planning',
              label: 'Path Planning'
            },
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/nav2/bipedal-navigation',
              label: 'Bipedal Navigation'
            },
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/nav2/obstacle-avoidance',
              label: 'Obstacle Avoidance'
            },
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/nav2/exercises',
              label: 'Exercises'
            }
          ]
        },
        {
          type: 'category',
          label: 'Assessments',
          items: [
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/assessments/index',
              label: 'Assessment Overview'
            },
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/assessments/isaac-sim-assessment',
              label: 'Isaac Sim Assessment'
            },
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/assessments/isaac-ros-assessment',
              label: 'Isaac ROS Assessment'
            },
            {
              type: 'doc',
              id: 'module-3-ai-robot-brain/assessments/nav2-assessment',
              label: 'Nav2 Assessment'
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        {
          type: 'doc',
          id: 'module-4-vla/demo-guide',
          label: 'Demo Guide'
        },
        {
          type: 'doc',
          id: 'module-4-vla/quickstart',
          label: 'Quickstart Guide'
        },
        {
          type: 'category',
          label: 'Voice-to-Action',
          items: [
            {
              type: 'doc',
              id: 'module-4-vla/voice-to-action/whisper-setup',
              label: 'Whisper Setup'
            },
            {
              type: 'doc',
              id: 'module-4-vla/voice-to-action/audio-processing',
              label: 'Audio Processing'
            },
            {
              type: 'doc',
              id: 'module-4-vla/voice-to-action/exercises',
              label: 'Exercises'
            }
          ]
        },
        {
          type: 'category',
          label: 'Cognitive Planning',
          items: [
            {
              type: 'doc',
              id: 'module-4-vla/cognitive-planning/planning-algorithms',
              label: 'Planning Algorithms'
            },
            {
              type: 'doc',
              id: 'module-4-vla/cognitive-planning/ros2-conversion',
              label: 'ROS 2 Conversion'
            },
            {
              type: 'doc',
              id: 'module-4-vla/cognitive-planning/exercises',
              label: 'Exercises'
            }
          ]
        },
        {
          type: 'category',
          label: 'Autonomous Execution',
          items: [
            {
              type: 'doc',
              id: 'module-4-vla/autonomous-execution/task-execution',
              label: 'Task Execution'
            },
            {
              type: 'doc',
              id: 'module-4-vla/autonomous-execution/capstone-project',
              label: 'Capstone Project'
            },
            {
              type: 'doc',
              id: 'module-4-vla/autonomous-execution/exercises',
              label: 'Exercises'
            }
          ]
        },
        {
          type: 'category',
          label: 'Assessments',
          items: [
            {
              type: 'doc',
              id: 'module-4-vla/assessments/vla-assessment',
              label: 'VLA Assessment'
            },
            {
              type: 'doc',
              id: 'module-4-vla/assessments/rubrics',
              label: 'Rubrics'
            }
          ]
        }
      ]
    }
  ],
};

// Alternative: Keep both autogenerated and manual sidebar
// tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
// ros2Sidebar: [
//   {
//     type: 'category',
//     label: 'Module 1: The Robotic Nervous System',
//     items: [
//       {
//         type: 'doc',
//         id: 'module-1/chapter-1-ros2-basics',
//         label: 'Chapter 1: ROS 2 Basics'
//       },
//       {
//         type: 'doc',
//         id: 'module-1/chapter-2-rclpy-bridge',
//         label: 'Chapter 2: Python-ROS Bridge (rclpy)'
//       },
//       {
//         type: 'doc',
//         id: 'module-1/chapter-3-urdf-modeling',
//         label: 'Chapter 3: Humanoid Description (URDF)'
//       }
//     ]
//   }
// ],

export default sidebars;
